[ADD] the method and view form to add reviews on an item
DanielHernandezO/TheKingdomOfBricks pull request #37
Opened 2023-03-28 05:18 UTC by Juanda0

In this PR I:

- Created the route to add reviews on items
- Added the rout to the web file
- Edited the view adding a form that allows the creation of the review

2023-03-28 05:29 UTC, Jguerra47 approved these changes

2023-03-28 10:51 UTC, DanielHernandezO reviewed
Checking styles

2023-03-28 10:52 UTC, DanielHernandezO requested changes
Styles

2023-03-29 01:42 UTC, DanielHernandezO approved these changes

2023-03-29 01:45 UTC, DanielHernandezO approved these changes
LGTM

2023-03-29 01:45 UTC, merged